// Package stack renders the Docker deployment and drives it: writing the
// compose file, proxy config and control scripts, starting the containers,
// waiting for each service to answer, and creating the storage buckets the
// application uploads into.
package stack

import (
	"bytes"
	"context"
	"crypto/tls"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/harsizcool/omegacases/installer/internal/config"
	"github.com/harsizcool/omegacases/installer/internal/runner"
	"github.com/harsizcool/omegacases/installer/internal/ui"
)

//go:embed templates
var templates embed.FS

// Stack operates on one generated deployment.
type Stack struct {
	cfg *config.Config
	run *runner.Runner
}

// New binds a stack to its config and command runner.
func New(cfg *config.Config, r *runner.Runner) *Stack { return &Stack{cfg: cfg, run: r} }

type templateData struct {
	Local           bool
	TLS             bool
	HTTPPort        string
	HTTPSPort       string
	PublicURL       string
	PasswordLiteral string
}

func (s *Stack) data() templateData {
	return templateData{
		Local:     s.cfg.DBMode == config.DBLocal,
		TLS:       s.cfg.Exposure == config.ExposeDomain,
		HTTPPort:  s.cfg.HTTPPort,
		HTTPSPort: s.cfg.HTTPSPort,
		PublicURL: s.cfg.PublicURL(),
		// Quoted as a SQL literal so a generated password can never break the
		// statement it is embedded in.
		PasswordLiteral: sqlLiteral(s.cfg.PostgresPassword),
	}
}

// Write renders every generated file into the stack directory.
func (s *Stack) Write() error {
	dir := s.cfg.StackDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	data := s.data()

	rendered := []struct {
		tmpl, out string
		mode      os.FileMode
	}{
		{"docker-compose.yml.tmpl", "docker-compose.yml", 0o644},
		{"Caddyfile.tmpl", "Caddyfile", 0o644},
		{"bootstrap.sql.tmpl", "bootstrap.sql", 0o600},
		{"start.cmd.tmpl", "start.cmd", 0o755},
		{"stop.cmd.tmpl", "stop.cmd", 0o755},
		{"omega.sh.tmpl", "omega.sh", 0o755},
	}
	for _, item := range rendered {
		body, err := templates.ReadFile("templates/" + item.tmpl)
		if err != nil {
			return err
		}
		t, err := template.New(item.tmpl).Parse(string(body))
		if err != nil {
			return fmt.Errorf("template %s is malformed: %w", item.tmpl, err)
		}
		var buf bytes.Buffer
		if err := t.Execute(&buf, data); err != nil {
			return fmt.Errorf("cannot render %s: %w", item.tmpl, err)
		}
		out := buf.Bytes()
		if item.out == "omega.sh" {
			out = []byte(strings.ReplaceAll(string(out), "\r\n", "\n"))
		}
		if err := os.WriteFile(filepath.Join(dir, item.out), out, item.mode); err != nil {
			return err
		}
	}

	// Copied verbatim, no substitution needed.
	for _, name := range []string{"Dockerfile.web", "Dockerfile.web.dockerignore"} {
		body, err := templates.ReadFile("templates/" + name)
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, name), body, 0o644); err != nil {
			return err
		}
	}

	return s.writeStackEnv()
}

// writeStackEnv writes the .env Compose reads for variable substitution.
func (s *Stack) writeStackEnv() error {
	anon, service := s.cfg.Keys()
	site := s.cfg.Domain
	if s.cfg.Exposure != config.ExposeDomain {
		// A bare port tells Caddy to serve HTTP on that port for any hostname,
		// which covers localhost and the machine's LAN address alike.
		site = ":80"
	}

	env := map[string]string{
		"SITE_ADDRESS":                  site,
		"ACME_EMAIL":                    s.cfg.ACMEEmail,
		"NEXT_PUBLIC_SUPABASE_URL":      s.cfg.SupabaseEndpoint(),
		"NEXT_PUBLIC_SUPABASE_ANON_KEY": anon,
		"SUPABASE_SERVICE_ROLE_KEY":     service,
		"NEXT_PUBLIC_APP_URL":           s.cfg.PublicURL(),
		"NOWPAYMENTS_API_KEY":           s.cfg.NowPaymentsAPIKey,
		"NOWPAYMENTS_IPN_SECRET":        s.cfg.NowPaymentsIPNSecret,
		"DISCORD_WEBHOOK_URL":           s.cfg.DiscordWebhook,
	}
	if s.cfg.DBMode == config.DBLocal {
		// The site's own server-side code cannot call the public origin from
		// inside the container — that address resolves back to the site itself.
		// This is the proxy's address on the container network, which serves the
		// same routes.
		env["SUPABASE_INTERNAL_URL"] = "http://proxy:8080"
		env["POSTGRES_PASSWORD"] = s.cfg.PostgresPassword
		env["JWT_SECRET"] = s.cfg.JWTSecret
		env["ANON_KEY"] = s.cfg.AnonKey
		env["SERVICE_ROLE_KEY"] = s.cfg.ServiceRoleKey
		env["REALTIME_ENC_KEY"] = s.cfg.RealtimeEncKey
		env["REALTIME_SECRET_KEY_BASE"] = s.cfg.RealtimeSecret
	}

	header := "# Generated by the OmegaCases setup program — these are the secrets the\n" +
		"# containers run with. Keep this file private and back it up: the keys in it\n" +
		"# are what the site's data is signed with.\n\n"
	_, err := config.WriteEnvFile(filepath.Join(s.cfg.StackDir(), ".env"), header, env)
	return err
}

// compose runs a compose subcommand against the generated stack.
func (s *Stack) compose(args []string, opts ...runner.Option) (string, error) {
	full := append([]string{"compose"}, args...)
	opts = append(opts, runner.In(s.cfg.StackDir()))
	return s.run.Run("docker", full, opts...)
}

// Build builds the site image. It is separated from Up so the long step can be
// announced on its own.
func (s *Stack) Build() error {
	_, err := s.compose([]string{"build", "--pull", "web"},
		runner.Stream(), runner.Timeout(40*time.Minute))
	return err
}

// Up starts everything in the background.
func (s *Stack) Up() error {
	_, err := s.compose([]string{"up", "-d", "--remove-orphans"},
		runner.Stream(), runner.Timeout(20*time.Minute))
	return err
}

// UpService starts one service and its dependencies.
func (s *Stack) UpService(name string) error {
	_, err := s.compose([]string{"up", "-d", name}, runner.Stream(), runner.Timeout(15*time.Minute))
	return err
}

// Down stops the containers, leaving the data volumes in place.
func (s *Stack) Down() error {
	_, err := s.compose([]string{"down"}, runner.Stream(), runner.Timeout(5*time.Minute))
	return err
}

// Status prints the container table.
func (s *Stack) Status() error {
	_, err := s.compose([]string{"ps"}, runner.Stream(), runner.Timeout(2*time.Minute))
	return err
}

// Logs returns the recent log lines for a service, for use in error reports.
func (s *Stack) Logs(service string, lines int) string {
	out, _ := s.compose([]string{"logs", "--no-color", fmt.Sprintf("--tail=%d", lines), service},
		runner.Timeout(2*time.Minute))
	return out
}

// WaitForDatabase blocks until Postgres accepts connections.
func (s *Stack) WaitForDatabase(limit time.Duration) error {
	deadline := time.Now().Add(limit)
	for {
		out, err := s.compose([]string{"exec", "-T", "db", "pg_isready", "-U", "postgres"},
			runner.Timeout(60*time.Second))
		if err == nil && strings.Contains(out, "accepting connections") {
			return nil
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("the database did not become ready within %s", limit)
		}
		time.Sleep(3 * time.Second)
	}
}

// ExecSQL runs a script against the database as the superuser, reporting the
// first error rather than pressing on, so a broken migration is visible.
func (s *Stack) ExecSQL(sql string) (string, error) {
	return s.compose(
		[]string{"exec", "-T", "db", "psql", "-U", "postgres", "-d", "postgres",
			"-v", "ON_ERROR_STOP=1", "--no-psqlrc", "-f", "-"},
		runner.Stdin(strings.NewReader(sql)),
		runner.Timeout(10*time.Minute),
	)
}

// QuerySQL runs a single query and returns the unaligned, headerless result,
// which keeps parsing on the Go side trivial.
func (s *Stack) QuerySQL(query string) (string, error) {
	out, err := s.compose(
		[]string{"exec", "-T", "db", "psql", "-U", "postgres", "-d", "postgres",
			"-v", "ON_ERROR_STOP=1", "--no-psqlrc", "-At", "-c", query},
		runner.Timeout(2*time.Minute),
	)
	return strings.TrimSpace(out), err
}

// RestartDatabase is needed after the bootstrap script changes server-level
// settings such as wal_level.
func (s *Stack) RestartDatabase() error {
	if _, err := s.compose([]string{"restart", "db"}, runner.Timeout(5*time.Minute)); err != nil {
		return err
	}
	return s.WaitForDatabase(3 * time.Minute)
}

// ─── HTTP probes ────────────────────────────────────────────────────────────

func httpClient() *http.Client {
	return &http.Client{
		Timeout: 15 * time.Second,
		Transport: &http.Transport{
			// The certificate may still be being issued when the first probe
			// runs, and a self-signed intermediate is not a reason to call the
			// deployment broken.
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, //nolint:gosec
		},
	}
}

// probeClient reaches the deployment the way a visitor would — same URL, same
// Host header, same certificate — but connects to the published port on this
// machine instead of resolving the domain. That matters twice: the domain's DNS
// may still be propagating, and a router that does not support hairpin NAT
// would fail to route the machine's own traffic back to itself.
func (s *Stack) probeClient() *http.Client {
	client := httpClient()
	if s.cfg.Exposure != config.ExposeDomain {
		return client
	}
	transport := client.Transport.(*http.Transport).Clone()
	dialer := &net.Dialer{Timeout: 10 * time.Second}
	transport.DialContext = func(ctx context.Context, network, addr string) (net.Conn, error) {
		host, port, err := net.SplitHostPort(addr)
		if err == nil && host == s.cfg.Domain {
			addr = net.JoinHostPort("127.0.0.1", port)
		}
		return dialer.DialContext(ctx, network, addr)
	}
	client.Transport = transport
	return client
}

// WaitForHTTP polls a URL until it answers with any status below 500.
func WaitForHTTP(url string, limit time.Duration) (int, error) {
	return waitForHTTP(httpClient(), url, limit)
}

func waitForHTTP(client *http.Client, url string, limit time.Duration) (int, error) {
	deadline := time.Now().Add(limit)
	var lastErr error
	for {
		resp, err := client.Get(url)
		if err == nil {
			io.Copy(io.Discard, io.LimitReader(resp.Body, 4096))
			resp.Body.Close()
			if resp.StatusCode < 500 {
				return resp.StatusCode, nil
			}
			lastErr = fmt.Errorf("%s replied %d", url, resp.StatusCode)
		} else {
			lastErr = err
		}
		if time.Now().After(deadline) {
			return 0, fmt.Errorf("%s did not answer within %s: %w", url, limit, lastErr)
		}
		time.Sleep(4 * time.Second)
	}
}

// WaitForSite waits until the proxy serves the application.
func (s *Stack) WaitForSite(limit time.Duration) error {
	_, err := waitForHTTP(s.probeClient(), s.cfg.PublicURL()+"/", limit)
	return err
}

// CheckDataAPI confirms the anon key can read through PostgREST end to end,
// which is the single most useful signal that the whole chain works.
func (s *Stack) CheckDataAPI() error {
	anon, _ := s.cfg.Keys()
	base := s.cfg.SupabaseEndpoint()
	req, err := http.NewRequest("GET", base+"/rest/v1/items?select=id&limit=1", nil)
	if err != nil {
		return err
	}
	req.Header.Set("apikey", anon)
	req.Header.Set("Authorization", "Bearer "+anon)

	resp, err := s.probeClient().Do(req)
	if err != nil {
		return fmt.Errorf("the data API could not be reached: %w", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 2048))
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("the data API replied %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}
	return nil
}

// EnsureBuckets creates the two storage buckets the app uploads into, both
// public so image URLs work without a signed request.
func (s *Stack) EnsureBuckets(names ...string) error {
	_, service := s.cfg.Keys()
	base := s.cfg.SupabaseEndpoint()
	client := s.probeClient()
	if _, err := waitForHTTP(client, base+"/storage/v1/bucket", 3*time.Minute); err != nil {
		return fmt.Errorf("the storage service did not come up: %w", err)
	}

	for _, name := range names {
		payload, err := json.Marshal(map[string]any{
			"id":     name,
			"name":   name,
			"public": true,
		})
		if err != nil {
			return err
		}
		req, err := http.NewRequest("POST", base+"/storage/v1/bucket", bytes.NewReader(payload))
		if err != nil {
			return err
		}
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("apikey", service)
		req.Header.Set("Authorization", "Bearer "+service)

		resp, err := client.Do(req)
		if err != nil {
			return fmt.Errorf("could not create the %q bucket: %w", name, err)
		}
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 2048))
		resp.Body.Close()

		switch {
		case resp.StatusCode < 300:
			ui.Done("storage bucket %q created", name)
		case strings.Contains(strings.ToLower(string(body)), "already exists"),
			resp.StatusCode == http.StatusConflict:
			ui.Done("storage bucket %q already present", name)
		default:
			return fmt.Errorf("could not create the %q bucket: %s replied %s",
				name, base, strings.TrimSpace(string(body)))
		}
	}
	return nil
}

func sqlLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// RegisterUser creates an account through the site's own signup route, so the
// password is hashed exactly the way the login page will check it.
//
// The request is made from inside the web container against the application
// directly. Calling in from outside would have to go through the proxy, which
// only answers to the site's own hostname — and that hostname resolves back to
// this machine, which is the problem being avoided.
func (s *Stack) RegisterUser(username, password string) error {
	payload, err := json.Marshal(map[string]string{"username": username, "password": password})
	if err != nil {
		return err
	}
	// The credentials travel as a here-doc on stdin rather than on the command
	// line, where they would be visible in the process list.
	script := `const body = require('fs').readFileSync(0, 'utf8');
fetch('http://127.0.0.1:3000/api/auth/register', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body,
}).then(async (r) => {
  const text = await r.text();
  if (!r.ok) { console.error('HTTP ' + r.status + ': ' + text); process.exit(1); }
  console.log('ok');
}).catch((e) => { console.error(String(e)); process.exit(1); });`

	out, err := s.compose(
		[]string{"exec", "-T", "web", "node", "-e", script},
		runner.Stdin(bytes.NewReader(payload)),
		runner.Timeout(2*time.Minute),
	)
	if err != nil {
		return fmt.Errorf("%s", strings.TrimSpace(lastLine(out)))
	}
	return nil
}

func lastLine(s string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	return lines[len(lines)-1]
}

// RestartService restarts one service. Storage and Realtime run their own
// migrations when they connect, and both start before the database roles they
// need exist, so they get one restart once setup has prepared the database.
func (s *Stack) RestartService(name string) error {
	_, err := s.compose([]string{"restart", name}, runner.Timeout(5*time.Minute))
	return err
}
